### ISSUE TITLE
Create test script with Sellenium library

### ISSUE THREAD

**Issue by iben0402** [Teravista/BE#13]
Create a script that uses a sellenium library and does the following things:
- Add 10 products with various amounts from 2 different categories to chart
- Search product by name and add random found product to chart
- Remove 3 products from chart
- Register new account
- Placing an order for the contents of the chart
- Choosing payment method: upon delivery
- Selection of one of two carriers,
- Approve order
- Check order status
- Download invoice

everything has to happend in 5 minutes

**Comment by mikibak** [comment]
Finish script
